---
abstract: 'A Cxn implementation which uses libcurl via Net::Curl'
author:
  - 'Clinton Gormley <drtech@cpan.org>'
build_requires:
  Cpanel::JSON::XS: '0'
  Data::Dumper: '0'
  File::Temp: '0'
  JSON::PP: '0'
  JSON::XS: '0'
  Log::Any::Adapter: '0'
  Log::Any::Adapter::Callback: '0'
  POSIX: '0'
  Sub::Exporter: '0'
  Test::Deep: '0'
  Test::Exception: '0'
  Test::More: '0.98'
  lib: '0'
  strict: '0'
  warnings: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.140640'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Search-Elasticsearch-Cxn-NetCurl
recommends:
  JSON::XS: '0'
  URI::Escape::XS: '0'
requires:
  HTTP::Parser::XS: '0'
  Moo: '0'
  Net::Curl::Easy: '0'
  Search::Elasticsearch: '1.15'
  Try::Tiny: '0'
  namespace::clean: '0'
resources:
  bugtracker: https://github.com/elasticsearch/elasticsearch-perl/issues
  repository: git://github.com/elasticsearch/elasticsearch-perl.git
version: '1.15'
